language: generic
os: osx
osx_image: xcode7.3
env: 
- TARGET_SYSTEM=OSX
  PYTHON=$HOME/homebrew/bin/python
  JOBS="`sysctl -n hw.ncpu`"
  MACOSX_DEPLOYMENT_TARGET=10.8
  HOMEBREW_NO_AUTO_UPDATE=1
  PATH=$HOME/homebrew/opt/python/libexec/bin:$HOME/homebrew/bin:$PATH
  LD_LIBRARY_PATH=$HOME/homebrew/lib:$LD_LIBRARY_PATH
  PKG_CONFIG_PATH=$HOME/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH
  CACHEFILE=homebrew-cache-pf-step4.tar.gz
  CACHEURL=https://github.com/aferrero2707/pf-build-osx/releases/download/continuous/$CACHEFILE
  #JPEG=/usr/local/opt/mozjpeg
before_script:
- ls /usr/local/bin
- sudo mv /usr/local/bin /usr/local/bin_
- sudo mv /usr/local/lib /usr/local/lib_
- sudo mv /usr/local/opt /usr/local/opt_
- travis_wait 120 sleep infinity & (cd $HOME && curl -L $CACHEURL -O && tar xzf $CACHEFILE && rm -f $CACHEFILE)
- ls -lh $HOME/homebrew/Cellar/exiv2/0.26/lib
#- nm -g -C $HOME/homebrew/Cellar/exiv2/0.26/lib/libexiv2.dylib  | grep Factory
#- find $HOME -name "*exiv2*"
#- sudo find /usr -name "*exiv2*"
- ./build-hb.sh
- ./package-gimp-hb.sh
- wget -c https://github.com/aferrero2707/uploadtool/raw/master/remove.sh
- bash ./remove.sh "continuous" "gimp-osx-" ".dmg"
- wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
- bash  ./upload_rotate.sh "continuous" $HOME/gimp-osx-*.dmg > /dev/null;


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
